from tkinter import *
window=Tk()
window.title("login form")
window.geometry("340x440")
# window.configure(bg='#333333')
label1=Label(window,text="Login")
label1.grid(row=0,column=1,columnspan=2)
username_label=Label(window,text="Username")
username_label.grid(column=0,row=1)
username_entry=Entry(window)
username_entry.grid(column=1,row=1)
password_label=Label(window,text="password")
password_label.grid(column=0,row=2)
password_entry=Entry(window,show="*")
password_entry.grid(column=1,row=2)
login_button=Button(window,text="login")
login_button.grid(column=1,row=3)

window.mainloop()